### ISSUE TITLE
Failure to load on Mac with Gramps 5.2 RC1

### ISSUE THREAD

**Issue by GaryGriffin** [jmichault/gramps-kromprogramoj#10]
Followed instructions to load for 5.2 RC1 on Mac M3 (using ARM dmg). 

I tried with and without the Addon Manager Setting: Allow Gramps to install required Python modules.

The following warnings and errors occurred:

WARNING:._manager:Plugin error (from 'PersonFS'): No module named 'packaging'
2024-02-11 12:56:24.216: WARNING: _manager.py: line 333: Plugin error (from 'PersonFS'): No module named 'packaging'
WARNING:._manager:Plugin error (from 'Importo'): No module named 'packaging'
2024-02-11 12:56:30.521: WARNING: _manager.py: line 333: Plugin error (from 'Importo'): No module named 'packaging'
WARNING:._manager:Plugin error (from 'komparo'): No module named 'gedcomx'
2024-02-11 12:56:32.402: WARNING: _manager.py: line 333: Plugin error (from 'komparo'): No module named 'gedcomx'
WARNING:._manager:Plugin error (from 'PersonFS'): No module named 'packaging'
2024-02-11 12:56:47.663: WARNING: _manager.py: line 333: Plugin error (from 'PersonFS'): No module named 'packaging'
WARNING:._manager:Plugin error (from 'PersonFS'): No module named 'packaging'
2024-02-11 12:56:47.664: WARNING: _manager.py: line 333: Plugin error (from 'PersonFS'): No module named 'packaging'
WARNING:.:Error loading gramplet 'FS Gramplet': skipping content
2024-02-11 12:56:47.664: WARNING: grampletpane.py: line 192: Error loading gramplet 'FS Gramplet': skipping content
ERROR:.:Unhandled exception
Traceback (most recent call last):
  File "/Users/gary/Applications/Gramps5.2-rc1.app/Contents/Resources/lib/python3.10/site-packages/gramps/gui/widgets/grampletbar.py", line 478, in __page_added
    gramplet.set_orientation(self.orientation)
  File "/Users/gary/Applications/Gramps5.2-rc1.app/Contents/Resources/lib/python3.10/site-packages/gramps/gui/widgets/grampletbar.py", line 693, in set_orientation
    self.pui.set_orientation(orientation)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_orientation'

**Comment by GaryGriffin** [comment]
Manually installed the following packages to the folder: Contents/Resources/lib/python3.11 

to make it work on the Mac. Also had to comment out the references to pip. Mac does not include pip in its bundle. 

concurrent
asyncio
certifi
idna
charset_normalizer
urllib3
gedcomx_v1
requests
packaging
setuptools
