### ISSUE TITLE
 ERROR: grampsapp.py: line 188: Unhandled exception Traceback (most recent call last):

### ISSUE THREAD

**Issue by avma** [jmichault/gramps-kromprogramoj#21]
User Information: 
===================
Sometimes'(its not consistent) when marking more then just one of the allowed check boxes, or checking a 'marriage' event type' this errors pop up.
I'm assuming this is related to the add-on since it is not happening otherwise.
Error Details: 
===================

2334658: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/home/avi/.local/share/gramps/gramps52/plugins/PersonFS/PersonFS.py", line 716, in <lambda>
    item.connect("activate",lambda obj: self.kopii_al_FS(treeview))
  File "/home/avi/.local/share/gramps/gramps52/plugins/PersonFS/PersonFS.py", line 552, in kopii_al_FS
    if res.status_code == 201 or res.status_code == 204:
AttributeError: 'NoneType' object has no attribute 'status_code'

System Information: 
===================

Gramps version: 5.2.0 
Python version: 3.10.12 
BSDDB version: 6.2.9 (5, 3, 28) 
sqlite version: 3.37.2 (2.6.0) 
LANG: he_IL.UTF-8
OS: Linux
Distribution: 5.15.0-101-generic

GTK version    : 3.24.33
gobject version: 3.42.1
cairo version  : (1, 20, 1)

**Comment by jmichault** [comment]
I think it's corrected in the current release.
