### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_orientation' when enabling Fs gramplet

### ISSUE THREAD

**Issue by MandyShaw** [jmichault/gramps-kromprogramoj#27]
Hi, I have just installed Gramps AIO64-5.2.2-r1-f905d14 (Windows 11) and successfully added version 2.0.37 of this FS add-on project,

When I try to enable the fs gramplet, I get an error as follows:
699599: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gui\widgets\grampletbar.py", line 478, in __page_added
    gramplet.set_orientation(self.orientation)
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gui\widgets\grampletbar.py", line 693, in set_orientation
    self.pui.set_orientation(orientation)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_orientation'

The Fs tab appears, but is blank.
Help appreciated - thanks.

**Comment by jmichault** [comment]
can you run gramps-console and note all messages in the console window ?

**Comment by MandyShaw** [comment]
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gen\plug\_manager.py", line 274, in load_plugin
    _module = self.import_plugin(pdata)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gen\plug\_manager.py", line 338, in import_plugin
    module = __import__(pdata.mod_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shaw_\AppData\Roaming\gramps\gramps52\plugins\PersonFS\PersonFS.py", line 101, in <module>
    gi.require_version("WebKit2", "4.0")        # Web content engine
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "AIO/gi/__init__.py", line 126, in require_version
ValueError: Namespace WebKit2 not available
2024-06-24 17:27:31.956: WARNING: grampletpane.py: line 192: Error loading gramplet 'FS Gramplet': skipping content
2024-06-24 17:27:31.958: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gui\widgets\grampletbar.py", line 478, in __page_added
    gramplet.set_orientation(self.orientation)
  File "C:\Program Files\GrampsAIO64-5.2.2\gramps\gui\widgets\grampletbar.py", line 693, in set_orientation
    self.pui.set_orientation(orientation)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_orientation'

**Comment by MandyShaw** [comment]
Note that Gramps did find an old config file from 2022 (I had uninstalled it long since) in case that is in aby way relevant

**Comment by jmichault** [comment]
I have released a new version which should work on windows.

**Comment by MandyShaw** [comment]
Fine now thanks!
